### ISSUE TITLE
VCFlat with deepvariant input

### ISSUE THREAD

**Issue by J35P312** [arontommi/VCFlat#7]
Hello!
I have tried using vcflat on a deepvariant vcf, however it crashes:

singularity exec vcflat_latest.sif python -m vcflat -i P10051_107.clean.dedup.bam.vcf -o P10051_107.clean.dedup.bam.vcf.csv --keys "Sample #CHROM POS REF ALT Gene_name"
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/pip-packages/VCFlat/vcflat/__main__.py", line 15, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/pip-packages/VCFlat/vcflat/cli.py", line 54, in vcflat
    long_anno=long_anno)
  File "/pip-packages/VCFlat/vcflat/OutputHandle.py", line 11, in __init__
    keylist = vcffile.sanitize_keys(keys=keys)
  File "/pip-packages/VCFlat/vcflat/VcfParse.py", line 117, in sanitize_keys
    allkeys = self.get_header()
  File "/pip-packages/VCFlat/vcflat/VcfParse.py", line 105, in get_header
    for d in pars:
  File "/pip-packages/VCFlat/vcflat/VcfParse.py", line 94, in parse
    return_li = self.parse_line_list(split_line)
  File "/pip-packages/VCFlat/vcflat/VcfParse.py", line 64, in parse_line_list
    li = split_ref_alt(li)
  File "/pip-packages/VCFlat/vcflat/VcfParse.py", line 180, in split_ref_alt
    vsp = [int(i) for i in v.split(',')]
  File "/pip-packages/VCFlat/vcflat/VcfParse.py", line 180, in <listcomp>
    vsp = [int(i) for i in v.split(',')]
ValueError: invalid literal for int() with base 10: '0.22807'

It appears to be unhappy with the VAF field:

##FORMAT=<ID=VAF,Number=A,Type=Float,Description="Variant allele fractions.">

1	15274	.	A	G,T	61.2	PASS	.	GT:GQ:DP:AD:VAF:PL	1/2:3:57:0,13,44:0.22807,0.77193:58,57,39,57,0,0

It seems like vcflat wants to convert the entries in the VAF to int, this is not possible, as these entries are float.
Do you agree with this interpretation?

Thanks, and good luck!
//Jesper

**Comment by arontommi** [comment]
Hi and sorry for a late reply, it seems the singularity file has not been updated in a while. I have uploaded the most recent version of vcflat to dockerhub
